/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TabulasiRouteImport } from './routes/tabulasi'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SketchRouteImport } from './routes/sketch'
import { Route as PresentasiRouteImport } from './routes/presentasi'
import { Route as Model3DRouteImport } from './routes/model3d'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as IndexRouteImport } from './routes/index'

const TabulasiRoute = TabulasiRouteImport.update({
  id: '/tabulasi',
  path: '/tabulasi',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SketchRoute = SketchRouteImport.update({
  id: '/sketch',
  path: '/sketch',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentasiRoute = PresentasiRouteImport.update({
  id: '/presentasi',
  path: '/presentasi',
  getParentRoute: () => rootRouteImport,
} as any)
const Model3DRoute = Model3DRouteImport.update({
  id: '/model3d',
  path: '/model3d',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/model3d': typeof Model3DRoute
  '/presentasi': typeof PresentasiRoute
  '/sketch': typeof SketchRoute
  '/studio': typeof StudioRoute
  '/tabulasi': typeof TabulasiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/model3d': typeof Model3DRoute
  '/presentasi': typeof PresentasiRoute
  '/sketch': typeof SketchRoute
  '/studio': typeof StudioRoute
  '/tabulasi': typeof TabulasiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/model3d': typeof Model3DRoute
  '/presentasi': typeof PresentasiRoute
  '/sketch': typeof SketchRoute
  '/studio': typeof StudioRoute
  '/tabulasi': typeof TabulasiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gallery'
    | '/login'
    | '/model3d'
    | '/presentasi'
    | '/sketch'
    | '/studio'
    | '/tabulasi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gallery'
    | '/login'
    | '/model3d'
    | '/presentasi'
    | '/sketch'
    | '/studio'
    | '/tabulasi'
  id:
    | '__root__'
    | '/'
    | '/gallery'
    | '/login'
    | '/model3d'
    | '/presentasi'
    | '/sketch'
    | '/studio'
    | '/tabulasi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GalleryRoute: typeof GalleryRoute
  LoginRoute: typeof LoginRoute
  Model3DRoute: typeof Model3DRoute
  PresentasiRoute: typeof PresentasiRoute
  SketchRoute: typeof SketchRoute
  StudioRoute: typeof StudioRoute
  TabulasiRoute: typeof TabulasiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tabulasi': {
      id: '/tabulasi'
      path: '/tabulasi'
      fullPath: '/tabulasi'
      preLoaderRoute: typeof TabulasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sketch': {
      id: '/sketch'
      path: '/sketch'
      fullPath: '/sketch'
      preLoaderRoute: typeof SketchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentasi': {
      id: '/presentasi'
      path: '/presentasi'
      fullPath: '/presentasi'
      preLoaderRoute: typeof PresentasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model3d': {
      id: '/model3d'
      path: '/model3d'
      fullPath: '/model3d'
      preLoaderRoute: typeof Model3DRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GalleryRoute: GalleryRoute,
  LoginRoute: LoginRoute,
  Model3DRoute: Model3DRoute,
  PresentasiRoute: PresentasiRoute,
  SketchRoute: SketchRoute,
  StudioRoute: StudioRoute,
  TabulasiRoute: TabulasiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
